### ISSUE TITLE
Some models don't work

### ISSUE THREAD

**Issue by iHaagcom** [akx/ggify#1]
Unfortunately for ChatGLM6B it returned the following error: returned non-zero exit status 1 exit status

**Comment by iHaagcom** [comment]
Also falcon

**Comment by akx** [comment]
Please show the full output – the last line alone won't help much.

**Comment by passerhub** [comment]
when use the llama.cpp to convert the chagglm model, error stack:

python ../llama.cpp/convert.py models/THUDM__chatglm-6b/
Loading model file models/THUDM__chatglm-6b/pytorch_model-00001-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00001-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00002-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00003-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00004-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00005-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00006-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00007-of-00008.bin
Loading model file models/THUDM__chatglm-6b/pytorch_model-00008-of-00008.bin
Traceback (most recent call last):
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 1225, in <module>
    main()
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 1205, in main
    model_plus = load_some_model(args.model)
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 1128, in load_some_model
    model_plus = merge_multifile_models(models_plus)
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 635, in merge_multifile_models
    model = merge_sharded([mp.model for mp in models_plus])
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 614, in merge_sharded
    return {name: convert(name) for name in names}
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 614, in <dictcomp>
    return {name: convert(name) for name in names}
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 589, in convert
    lazy_tensors: List[LazyTensor] = [model[name] for model in models]
  File "/mnt/c/Projects/ggify/../llama.cpp/convert.py", line 589, in <listcomp>
    lazy_tensors: List[LazyTensor] = [model[name] for model in models]
KeyError: 'transformer.layers.0.attention.dense.bias'

**Comment by akx** [comment]
This has to do with `llama.cpp`'s `convert.py`, not this tool. You may need to use `--use-convert-hf-to-gguf` instead, too.
